### ISSUE TITLE
Polygon not displayed if vertices not in the field of view

### ISSUE THREAD

**Issue by vforchi** [cds-astro/aladin-lite#52]
I think this is a known bug, but I couldn't find an open issue for it.
When you draw a polygon and then zoom in on one of the sides, the side disappear as soon as the vertices are not in the field of view.
This is particularly a problem when the polygon represents a long slit, and you would like to zoom in in the center to make sure that your target is in the slit.

**Comment by vforchi** [comment]
Here the slit is displayed.
<img width="546" alt="Screen Shot 2021-01-13 at 10 00 55" src="https://user-images.githubusercontent.com/10163979/104429978-76150600-5586-11eb-955f-d2f4accc7460.png">
Here it is not: note that this happens only when **no** vertices are in the field of view.
<img width="541" alt="Screen Shot 2021-01-13 at 10 01 04" src="https://user-images.githubusercontent.com/10163979/104429988-77dec980-5586-11eb-85df-d3ee599f8540.png">

**Comment by tboch** [comment]
This should be corrrected in Aladin Lite v3 (branch **develop**). Can you confirm it's ok at your side?

**Comment by vforchi** [comment]
I'm afraid it's not easy to replace v2 with v3 in our application.
Also, it's still in beta, so I don't feel confident in deploying it to production.
Is the development of v2 on hold?

**Comment by tboch** [comment]
Fair points.
V3 official release should happen shortly, next month.
I encourage you to test your application with AL v3 engine, and report any problem you might discover. It
The API has not changed, only the initialization code has evolved:
https://aladin.cds.unistra.fr/AladinLite/v3-beta/migration-guide/

Please note that v3 also fixes other bugs, like this one: https://github.com/cds-astro/aladin-lite/issues/20

If having this bug fixed in v2 is still a must, we will do it, but it's not easy as we have to retrofit Rust code (from v3) to a JS-only code base (in v2).

**Comment by bmatthieu3** [comment]
I will close the issue as Aladin lite v3 has been released. That bug do have been fixed in it.
